source ${HOME}/.config/nvim/general/setting.vim
source ${HOME}/.config/nvim/general/start_page.vim
source ${HOME}/.config/nvim/key/mappings.vim
source ${HOME}/.config/nvim/key/plugins.vim
source ${HOME}/.config/nvim/plugin/coc.vim
source ${HOME}/.config/nvim/plugin/vim_plug.vim
source ${HOME}/.config/nvim/plugin/plugin_setting.vim
source ${HOME}/.config/nvim/plugin/lightline.vim
source ${HOME}/.config/nvim/lua/init.lua
